version: "3.7"

services:
  caddy:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      #- ./_site:/srv:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
