services:
  caddy:
    build: .
    restart: unless-stopped
    ports:
      - "8080:80"
    #volumes:
      #- ./Caddyfile:/etc/caddy/Caddyfile:ro
      #- ./_site:/srv:ro
      #- ./caddy/config:/config
      #- ./caddy/data:/data
    #command: caddy run --config /etc/caddy/Caddyfile --watch
